name: Naukri Profile Update

on:
  schedule:
    # Runs every weekday (Monday to Friday) at 8:00 AM IST (2:30 AM UTC)
    - cron: '30 2 * * 1-5'
  push:
    # Run on any push to any branch
    branches:
      - '**'
  workflow_dispatch:
    # Allows manual triggering of the workflow
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual profile update'

jobs:
  update-profile:
    runs-on: ubuntu-latest
    environment: dev
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up environment variables
      run: |
        echo "NAUKRI_EMAIL=${{ secrets.NAUKRI_EMAIL }}" >> $GITHUB_ENV
        echo "NAUKRI_PASSWORD=${{ secrets.NAUKRI_PASSWORD }}" >> $GITHUB_ENV
    
    - name: Run profile updater
      env:
        NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
        NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
      run: |
        # Log trigger event information
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manual run triggered. Reason: ${{ github.event.inputs.reason || 'No reason provided' }}"
        elif [ "${{ github.event_name }}" == "push" ]; then
          echo "Triggered by push to branch: ${{ github.ref_name }}"
        else
          echo "Triggered by scheduled event"
        fi
        python resume_headline_sync.py
